image: node:10.8.0

pipelines:
 default:
  - step:
     caches:
      - node
     script: 
      - echo "variable ${API_KEY}"
      - npm install
      - npm test
      - IMAGE_NAME=rcastillejo/techu-project
      - VERSION="0.1.${BITBUCKET_BUILD_NUMBER}"
      - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
      - docker build -t ${IMAGE_NAME}:${VERSION} .
      - docker push "${IMAGE_NAME}:${VERSION}"