image: node:10.8.0

pipelines:
 default:
  - variables:
      API_KEY: $API_KEY
  - step:
     caches:
      - node
     script: 
      - echo 'variable ${API_KEY}'
      - npm install
      - npm test