pipelines:
 default:
  - step: 
     image: node:10.8.0
     name: build and test
     caches:
      - node
     script: 
      - echo "variable ${API_KEY}"
      - npm install
      - npm test
      - IMAGE_NAME=rcastillejo/techu-project
      - VERSION="0.1.${BITBUCKET_BUILD_NUMBER}"
      - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
      - docker build -t ${IMAGE_NAME}:${VERSION} .
      - docker push "${IMAGE_NAME}:${VERSION}"
      - docker tag ${IMAGE_NAME}:${VERSION} ${IMAGE_NAME}
      - docker push "${IMAGE_NAME}"
     services:
      - docker
  - step:
    name: Manual step
    trigger: manual
    script:
      - echo "This step runs once you click the 'Run' button"    
  - step:
      image: openshift/origin-cli
      name: Deploy to Openshift
      script:
        - oc login "https://${OPS_INSTANCE}.environments.katacoda.com:443" -u developer -p developer
        - oc project myproject
        - oc tag rcastillejo/techu-project myproject:latest
        - oc get -o template route myproject --template={{.spec.host}}